FROM dunglas/frankenphp:php8.4

# PHP extensions
RUN install-php-extensions \
    pdo_pgsql \
    pgsql \
    mbstring \
    bcmath \
    exif \
    pcntl \
    intl \
    zip

WORKDIR /app

# Copy project
COPY . .

# Hapus cache Laravel lama
RUN rm -f bootstrap/cache/*.php

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader

# Generate Wayfinder
RUN php artisan wayfinder:generate --with-form

# Install frontend dependencies
RUN npm install

# Build frontend
RUN npm run build

# Start Laravel dengan FrankenPHP
CMD ["sh", "-c", "php artisan octane:frankenphp --server=frankenphp --host=0.0.0.0 --port=${PORT:-80} --workers=1 --max-requests=1"]