FROM dunglas/frankenphp:php8.4

# Install PHP extensions
RUN install-php-extensions \
    pdo_pgsql \
    pgsql \
    mbstring \
    bcmath \
    exif \
    pcntl \
    intl \
    zip

WORKDIR /app

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Copy project
COPY . .

# Hapus cache Laravel lama
RUN rm -f bootstrap/cache/*.php

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader

# Generate Wayfinder
RUN php artisan wayfinder:generate --with-form

# Install Node.js dan npm
RUN apt-get update && apt-get install -y nodejs npm \
    && rm -rf /var/lib/apt/lists/*

RUN npm install

RUN npm run build

CMD ["sh", "-c", "frankenphp php-server -r public/ --listen :${PORT:-80}"]